"""Public UI helpers for PromptPro CLI output."""

from src.ui.console import console
from src.ui.panels import (
    print_analysis,
    print_banner,
    print_divergent_questions,
    print_error,
    print_first_run_tips,
    print_framework_recommendation,
    print_help,
    print_info,
    print_prompt_panel,
    print_success,
    print_versions_prompt,
    print_warning,
    print_welcome_guide,
)
from src.ui.tables import (
    create_choice_table,
    create_data_table,
    show_config,
    show_config_table,
    show_doc_detail,
    show_docs_list,
    show_framework_components,
    show_framework_selection,
    show_frameworks,
    show_frameworks_table,
    show_history_detail,
    show_history_items,
    show_models,
    show_optimized_versions,
)

__all__ = [
    "console",
    "print_analysis",
    "print_banner",
    "print_divergent_questions",
    "print_error",
    "print_first_run_tips",
    "print_framework_recommendation",
    "print_help",
    "print_info",
    "print_prompt_panel",
    "print_success",
    "print_versions_prompt",
    "print_warning",
    "print_welcome_guide",
    "create_choice_table",
    "create_data_table",
    "show_config",
    "show_config_table",
    "show_doc_detail",
    "show_docs_list",
    "show_framework_components",
    "show_framework_selection",
    "show_frameworks",
    "show_frameworks_table",
    "show_history_detail",
    "show_history_items",
    "show_models",
    "show_optimized_versions",
]
